### PR TITLE
fix junit xml with testsuites tag

### LINKED ISSUE #1045: merge bot doesn't read the junit XML files that the unit tests make
...because they are named differently from the e2e tests.

I don't care if we change the unit test output or change the merge bot. @ixdy opinions?

### PR DESCRIPTION
**Pull request by freehan**
fix: #1045

### CODE REVIEW

**Comment by lavalamp** [comment]
awesome, thanks! LGTM

File: mungegithub/mungers/e2e/e2e.go [hunk 1]
```diff
@@ -231,21 +232,37 @@ func getJUnitFailures(r io.Reader) (failures map[string]string, err error) {
...
 	}
-	if ts.FailCount == 0 {
-		return nil, nil
+	// first try to parse the result with <testsuites> as top tag
+	err = xml.Unmarshal(b, testSuites)
+	if err == nil && len(testSuites.TestSuites) > 0 {
+		testSuiteList = testSuites.TestSuites
+	} else {
+		// second try to parse the result with <testsuite> as top tag
+		xml.Unmarshal(b, testSuite)
```
Comment (ixdy) [inline mungegithub/mungers/e2e/e2e.go]: this should be `err = xml.Unmarshal`

**Comment by lavalamp** [comment]
also needs a gofmt to make travis happy.

File: mungegithub/mungers/e2e/e2e.go [hunk 2]
```diff
@@ -231,21 +232,37 @@ func getJUnitFailures(r io.Reader) (failures map[string]string, err error) {
...
-	for _, tc := range ts.Testcases {
-		if tc.Failure != "" {
-			failures[fmt.Sprintf("%v {%v}", tc.Name, tc.ClassName)] = tc.Failure
+	for _, ts := range testSuiteList {
+		if ts.FailCount == 0 {
+			continue
+		}
+		for _, tc := range ts.Testcases {
+			if tc.Failure != "" {
+				failures[fmt.Sprintf("%v {%v}", tc.Name, tc.ClassName)] = tc.Failure
```
Comment (ixdy) [inline mungegithub/mungers/e2e/e2e.go]: the unit/integration runs have duplicates, since tests are currently run multiple times with different test api / etcd registry prefixes. probably need to handle that.

File: mungegithub/mungers/e2e/e2e.go (hunk 1 above)
Comment (freehan) [inline mungegithub/mungers/e2e/e2e.go]: Oh my... My bad...

File: mungegithub/mungers/e2e/e2e.go (hunk 2 above)
Comment (freehan) [inline mungegithub/mungers/e2e/e2e.go]: What about I add testsuite.name into the key?

Comment (lavalamp) [inline mungegithub/mungers/e2e/e2e.go]: Let's fix that in a separate step-- we need to be careful so we don't make a ton of duplicate issues.

Comment (freehan) [inline mungegithub/mungers/e2e/e2e.go]: True

Comment (ixdy) [inline mungegithub/mungers/e2e/e2e.go]: There isn't anything in the XML itself to differentiate the runs right now (though we should probably look into adding that). Compare https://console.cloud.google.com/m/cloudstorage/b/kubernetes-jenkins/o/logs/kubernetes-test-go/12970/artifacts/junit_v1%2Cautoscaling-v1%2Cbatch-v1%2Cbatch-v2alpha1%2Cextensions-v1beta1%2Capps-v1alpha1%2Cfederation-v1alpha1%2Cpolicy-v1alpha1%2Crbac.authorization.k8s.io-v1alpha1_20160612-085102.xml and
https://console.cloud.google.com/m/cloudstorage/b/kubernetes-jenkins/o/logs/kubernetes-test-go/12970/artifacts/junit_v1%2Cextensions-v1beta1%2Cfederation-v1alpha1_20160612-084419.xml, which are part of the same Jenkins run.

Comment (lavalamp) [inline mungegithub/mungers/e2e/e2e.go]: We can look at the file name if needed...

**Comment by lavalamp** [comment]
LGTM. Going to push shortly.
