### PR TITLE
Fix stats on retest-not-required merges

### LINKED ISSUE #1212: submit queue: merge rate broken
Shows as zero even though it's merging things. #1208 changes this but I don't see how it could break it.

### PR DESCRIPTION
**Pull request by lavalamp**
Fixes #1212

### CODE REVIEW

File: mungegithub/mungers/submit-queue.go [hunk 1]
```diff
@@ -287,13 +287,13 @@ func calcMergeRate(oldRate float64, last, now time.Time) float64 {
...
 // returns 'Now()' and the rate.
-// Should be called once after every merge. Also updates sq.totalMerges.
+// Note that this does not update sq.lastMergeTime-- that should be done with
+// every merge, but this function should not be called on retest-not-required
+// merges.
 func (sq *SubmitQueue) updateMergeRate() {
 	now := sq.clock.Now()
 
 	sq.mergeRate = calcMergeRate(sq.mergeRate, sq.lastMergeTime, now)
-	sq.lastMergeTime = now
```
Comment (eparis) [inline mungegithub/mungers/submit-queue.go]: hmmmm, moving this is going to throw off the rate calculation when the next NON-retest-not-required comes through, no?  I was using the merge rate to figure out 'how many real PRs it can do a day' but now if the bot blocks for 4 hours, restarts and merges a retest-not-required and then in 30 minutes minutes it will calculate on the last PR having taken 30 minutes instead of 4:30...

Comment (eparis) [inline mungegithub/mungers/submit-queue.go]: I could also be convinced all my crazy math just isn't worth it and we should just keep a list of the last X hours or merges and show the average...

Comment (lavalamp) [inline mungegithub/mungers/submit-queue.go]: > throw off the rate calculation when the next NON-retest-not-required comes through

I think that's a feature, not a bug. 

I think your math makes numbers that are generally in the right ballpark and we should not throw it away yet :)
