### PR TITLE
Cluster-autoscaler: fix for multi-mig autoscaling

### LINKED ISSUE #1283: Cluster autoscaler requires all migs to be autoscaled
Otherwise it doesn't do any scale up or scale down.

### PR DESCRIPTION
**Pull request by mwielgus**
cc: @fgrzadkowski @piosz @jszczepkowski 

Fixes #1283

### CODE REVIEW

**Comment by fgrzadkowski** [comment]
@mwielgus Please explain what is the bug and how do we fix this.

File: cluster-autoscaler/utils/gce/gce.go [hunk 1]
```diff
@@ -164,13 +177,23 @@ func (m *GceManager) GetMigForInstance(instance *config.InstanceConfig) (*config
...
 		return mig, nil
 	}
-	if err := m.regenerateCache(); err != nil {
-		return nil, fmt.Errorf("Error while looking for MIG for instance %+v, error: %v", *instance, err)
-	}
-	if mig, found := m.migCache[*instance]; found {
-		return mig, nil
+
+	for _, mig := range m.migs {
+
```
Comment (piosz) [inline cluster-autoscaler/utils/gce/gce.go]: remove empty line

**Comment by mwielgus** [comment]
Fixes: #1283

Previously we were rising an error if we didn't have mig config for all nodes in the cluster. This error was equivalent to cluster being not in stable state and preventing CA from any scale up or scale downs. Now we raise this error only if the node has the prefix corresponding to some mig base name but the mig doesn't have this node on the list. Otherwise we assume that the node belongs to non-autoscaled mig and continue with all activities.

**Comment by piosz** [comment]
LGTM
Please create an issue and add TODO somewhere to solve this problem better as we talked offline.

File: cluster-autoscaler/utils/gce/gce.go (hunk 1 above)
Comment (mwielgus) [inline cluster-autoscaler/utils/gce/gce.go]: Done

File: cluster-autoscaler/utils/gce/gce.go [hunk 2]
```diff
@@ -164,13 +177,22 @@ func (m *GceManager) GetMigForInstance(instance *config.InstanceConfig) (*config
...
-		return nil, fmt.Errorf("Error while looking for MIG for instance %+v, error: %v", *instance, err)
-	}
-	if mig, found := m.migCache[*instance]; found {
-		return mig, nil
+
+	for _, mig := range m.migs {
+		if mig.config.Project == instance.Project &&
+			mig.config.Zone == instance.Zone &&
+			strings.HasPrefix(instance.Name, mig.basename) {
+			if err := m.regenerateCache(); err != nil {
```
Comment (fgrzadkowski) [inline cluster-autoscaler/utils/gce/gce.go]: I think it'd be readable if you restructure the code such that:

1. in a for loop check if we have any corresponding loop
2. if we have a corresponding mig regenerate cache and return mig
3. if don't have it return nils

File: cluster-autoscaler/utils/gce/gce.go [hunk 3]
```diff
@@ -164,13 +177,22 @@ func (m *GceManager) GetMigForInstance(instance *config.InstanceConfig) (*config
...
+				return nil, fmt.Errorf("Error while looking for MIG for instance %+v, error: %v", *instance, err)
+			}
+			if mig, found := m.migCache[*instance]; found {
+				return mig, nil
+			}
+			return nil, fmt.Errorf("Instance %+v does not belong to any configured MIG", *instance)
+		}
 	}
-	return nil, fmt.Errorf("Instance %+v does not belong to any known MIG", *instance)
+	// Instance doesn't belong to any configured mig.
```
Comment (fgrzadkowski) [inline cluster-autoscaler/utils/gce/gce.go]: Please explain it's ok.

File: cluster-autoscaler/utils/gce/gce.go [hunk 4]
```diff
@@ -164,13 +177,22 @@ func (m *GceManager) GetMigForInstance(instance *config.InstanceConfig) (*config
...
-	if err := m.regenerateCache(); err != nil {
-		return nil, fmt.Errorf("Error while looking for MIG for instance %+v, error: %v", *instance, err)
-	}
-	if mig, found := m.migCache[*instance]; found {
-		return mig, nil
+
+	for _, mig := range m.migs {
+		if mig.config.Project == instance.Project &&
+			mig.config.Zone == instance.Zone &&
+			strings.HasPrefix(instance.Name, mig.basename) {
```
Comment (fgrzadkowski) [inline cluster-autoscaler/utils/gce/gce.go]: During the first run of this loop basename will be empty and it will always be a prefix and we'll return a prefix. Am I missing something?

**Comment by mwielgus** [comment]
@fgrzadkowski  sorry, too late, i will do it in a follow-up pr.

**Comment by fgrzadkowski** [comment]
@mwielgus At the very least please answer to my question regarding base name in the first run.

File: cluster-autoscaler/utils/gce/gce.go (hunk 4 above)
Comment (piosz) [inline cluster-autoscaler/utils/gce/gce.go]: Cache is 'regenerated' in the beginning, so this could happen only in case of race condition (with very low probability).
