### PR TITLE
WIP: [nginx-ingress-controller] Add support for rewrite

### LINKED ISSUE #860: Nginx Ingress Controller - the /foo redirection is not working ?
Hi guys,

I work with the Ingress / Nginx Ingress Controller, but i can't get the /foo redirection working.

I deployed on a Kubernetes cluster a daemonset of Nginx ingress controller, default backend is the http-default-backend example.

This is my ingress object : 

```
# apimobile Ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apimobile-map
spec:
  rules:
  - host: azure.coursierprive.com
    http:
      paths:
      - path: /apimobile
        backend:
          serviceName: application-apimobile
          servicePort: 80
  - host: kube-20160428-120550-loadbalancer.northeurope.cloudapp.azure.com
    http:
      paths:
      - path: /
        backend:
          serviceName: application-apimobile
          servicePort: 80

```

My second rule is working but not the first one, if i try to reach my api on : azure.coursierprive.com/apimobile 

I face the : backend - 404 

I tried with Jenkins portal instead of my API but i face the same problem.

### PR DESCRIPTION
**Pull request by aledbf**
fixes #860

### CODE REVIEW

File: ingress/controllers/nginx/nginx/rewrite/main.go [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+
+import (
+	"strconv"
+
+	"k8s.io/kubernetes/pkg/apis/extensions"
+)
+
+const (
+	rewriteTo  = "ingress-nginx.kubernetes.io/rewrite-to"
+	addBaseURL = "ingress-nginx.kubernetes.io/add-base-url"
```
Comment (bprashanth) [inline ingress/controllers/nginx/nginx/rewrite/main.go]: please add an example in the readme with how these interact with the controller and ingresses in the cluster

File: ingress/controllers/nginx/nginx/rewrite/main.go [hunk 2]
```diff
@@ -0,0 +1,84 @@
...
+
+	return false
+}
+
+func (a ingAnnotations) rewriteTo() string {
+	val, ok := a[rewriteTo]
+	if ok {
+		return val
+	}
+
```
Comment (bprashanth) [inline ingress/controllers/nginx/nginx/rewrite/main.go]: please drop this dead line, and the one above the return of the previous method

File: ingress/controllers/nginx/nginx/rewrite/main.go [hunk 3]
```diff
@@ -0,0 +1,84 @@
...
+	return ""
+}
+
+// ParseAnnotations parses the annotations contained in the ingress
+// rule used to rewrite the defined paths
+func ParseAnnotations(ing *extensions.Ingress) (*Redirect, error) {
+	if ing.GetAnnotations() == nil {
+		return &Redirect{}, ErrMissingAnnotations{"no annotations present"}
+	}
+
```
Comment (bprashanth) [inline ingress/controllers/nginx/nginx/rewrite/main.go]: can you just inline the 2 local vars into the struct?

File: ingress/controllers/nginx/nginx/rewrite/main.go [hunk 4]
```diff
@@ -0,0 +1,84 @@
...
+	rt := ingAnnotations(ing.GetAnnotations()).rewriteTo()
+	abu := ingAnnotations(ing.GetAnnotations()).addBaseURL()
+	return &Redirect{
+		To:         rt,
```
Comment (bprashanth) [inline ingress/controllers/nginx/nginx/rewrite/main.go]: can you name this field something else? maybe base/target, since that matches the html concept?

File: ingress/controllers/nginx/nginx/template.go [hunk 5]
```diff
@@ -100,3 +107,68 @@ func toCamelCase(src string) string {
 	}
 	return string(bytes.Join(chunks, nil))
 }
+
+func buildLocation(input interface{}) string {
```
Comment (bprashanth) [inline ingress/controllers/nginx/nginx/template.go]: please include a comment with an example output string so it's clear what role this function plays in producing the final template

File: ingress/controllers/nginx/nginx/template.go [hunk 6]
```diff
@@ -100,3 +107,68 @@ func toCamelCase(src string) string {
...
+
+	path := location.Path
+	if len(location.Redirect.To) > 0 && location.Redirect.To != path {
+		return fmt.Sprintf("~* %s", path)
+	}
+
+	return path
+}
+
+func buildProxyPass(input interface{}) string {
```
Comment (bprashanth) [inline ingress/controllers/nginx/nginx/template.go]: same as comment above, an example like: buildProxyPass produces the proxy pass string, if the ingress has redirects (specified through the kubernetes.io/... annotation), a base tag is added, eg: for an annotation like `kubernetes.io...` you will get: `<base href="http://">`...

File: ingress/controllers/nginx/nginx/rewrite/main.go [hunk 7]
```diff
@@ -0,0 +1,84 @@
...
+
+	"k8s.io/kubernetes/pkg/apis/extensions"
+)
+
+const (
+	rewriteTo  = "ingress-nginx.kubernetes.io/rewrite-to"
+	addBaseURL = "ingress-nginx.kubernetes.io/add-base-url"
+)
+
+// ErrMissingAnnotations is returned when the ingress rule
```
Comment (bprashanth) [inline ingress/controllers/nginx/nginx/rewrite/main.go]: why define a custom error type if you're not actually checking for it?

File: ingress/controllers/nginx/nginx/rewrite/main.go [hunk 8]
```diff
@@ -0,0 +1,84 @@
...
+
+package rewrite
+
+import (
+	"strconv"
+
+	"k8s.io/kubernetes/pkg/apis/extensions"
+)
+
+const (
```
Comment (bprashanth) [inline ingress/controllers/nginx/nginx/rewrite/main.go]: can you express this as a single annotation, they're tied together right? maybe just: `ingress.kubernetes.io/rewrite: {base, target}` ? you'd have to unmarshal a map but that's simple.

Also why `ingress-nginx`? just ignore the annotations you don't care about and use the rest? typically the first part of the annotations prefix is the resource name and has nothing to do with the implementation, and all site specific data is included after the "/"

**Comment by bprashanth** [comment]
Looks good, mostly just stylistic comments. Rewrites are so common that I think we should document this with ample examples (with without base, with regex etc).

File: ingress/controllers/nginx/nginx/rewrite/main.go (hunk 1 above)
Comment (aledbf) [inline ingress/controllers/nginx/nginx/rewrite/main.go]: yes, this is what's missing now

File: ingress/controllers/nginx/nginx/rewrite/main.go (hunk 8 above)
Comment (aledbf) [inline ingress/controllers/nginx/nginx/rewrite/main.go]: > Also why ingress-nginx?

No particular reason. Can I leave this change to the last PR before the release of the new version (other pr's use a similar prefix)

File: ingress/controllers/nginx/examples/rewrite/README.md [hunk 9]
```diff
@@ -0,0 +1,67 @@
+
+Create an Ingress rule with a rewrite annotation:
```
Comment (bprashanth) [inline ingress/controllers/nginx/examples/rewrite/README.md]: can you also add an examble with base path?

**Comment by bprashanth** [comment]
You have a merge conflict, LGTM but for the doc nit

File: ingress/controllers/nginx/examples/rewrite/README.md (hunk 9 above)
Comment (aledbf) [inline ingress/controllers/nginx/examples/rewrite/README.md]: yes, I'm searching for a sample app :)

**Comment by aledbf** [comment]
@bprashanth can we left the missing example for #1104?
