### PR TITLE
[nginx-ingress-controller]: Check for errors in nginx template

### LINKED ISSUE #1448: NGINX ingress - Invalid memory or nil pointer dereference
This issue started happening recently and I've been unable to tease out what the issue is thus far: Here are the error logs of my pod with --v=3

```
I0728 18:22:03.538191       1 main.go:99] Using build: https://github.com/bprashanth/contrib.git - git-b195d9b
I0728 18:22:03.850164       1 main.go:134] Validated kube-system/default-http-backend as the default backend
I0728 18:22:03.850325       1 utils.go:66] nameservers to use: [25.0.0.10]
W0728 18:22:03.850482       1 ssl.go:132] no file dhparam.pem found in secrets
I0728 18:22:03.903589       1 controller.go:1128] starting NGINX loadbalancer controller
I0728 18:22:03.903983       1 command.go:35] Starting NGINX process...
I0728 18:22:03.907639       1 reflector.go:213] Starting reflector *extensions.Ingress (30s) from k8s.io/contrib/ingress/controllers/nginx/controller.go:1131
I0728 18:22:03.907807       1 reflector.go:253] Listing and watching *extensions.Ingress from k8s.io/contrib/ingress/controllers/nginx/controller.go:1131
I0728 18:22:03.908725       1 reflector.go:213] Starting reflector *api.Endpoints (30s) from k8s.io/contrib/ingress/controllers/nginx/controller.go:1132
I0728 18:22:03.908783       1 reflector.go:253] Listing and watching *api.Endpoints from k8s.io/contrib/ingress/controllers/nginx/controller.go:1132
I0728 18:22:03.909050       1 reflector.go:213] Starting reflector *api.Service (30s) from k8s.io/contrib/ingress/controllers/nginx/controller.go:1133
I0728 18:22:03.909112       1 reflector.go:253] Listing and watching *api.Service from k8s.io/contrib/ingress/controllers/nginx/controller.go:1133
I0728 18:22:03.909336       1 reflector.go:213] Starting reflector *api.Secret (30s) from k8s.io/contrib/ingress/controllers/nginx/controller.go:1134
I0728 18:22:03.909367       1 reflector.go:253] Listing and watching *api.Secret from k8s.io/contrib/ingress/controllers/nginx/controller.go:1134
I0728 18:22:03.910913       1 reflector.go:213] Starting reflector *api.ConfigMap (30s) from k8s.io/contrib/ingress/controllers/nginx/controller.go:1135
I0728 18:22:03.910960       1 reflector.go:253] Listing and watching *api.ConfigMap from k8s.io/contrib/ingress/controllers/nginx/controller.go:1135
I0728 18:22:04.121433       1 utils.go:89] syncing kube-system/kube-controller-manager
I0728 18:22:05.122474       1 utils.go:91] requeuing kube-system/kube-controller-manager, err deferring sync till endpoints controller has synced
I0728 18:22:05.122565       1 utils.go:89] syncing default/kubernetes
I0728 18:22:05.125479       1 controller.go:992] getting endpoints for service kube-system/default-http-backend and port 8080
I0728 18:22:05.125534       1 controller.go:1060] endpoints found: [{25.1.36.2 8080 0 0} {25.1.39.2 8080 0 0} {25.1.66.2 8080 0 0}]
I0728 18:22:05.126085       1 ssl.go:111] found [b7067b2f53db] common names: 1
I0728 18:22:05.126229       1 controller.go:992] getting endpoints for service kube-system/default-http-backend and port 8080
I0728 18:22:05.126260       1 controller.go:1060] endpoints found: [{25.1.36.2 8080 0 0} {25.1.39.2 8080 0 0} {25.1.66.2 8080 0 0}]
W0728 18:22:05.126321       1 utils.go:231] system net.core.somaxconn=128. Using NGINX default (511)
I0728 18:22:05.126877       1 template.go:79] NGINX configuration: {"backlogSize":511,"cfg":{"bodySize":"0m","customHttpErrors":[],"enableDynamicTlsRecords":true,"enableSpdy":true,"errorLogLevel":"notice","gzipTypes":"application/atom+xml application/javascript application/json application/rss+xml application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/svg+xml image/x-icon text/css text/plain text/x-component","hsts":true,"hstsIncludeSubdomains":true,"hstsMaxAge":"15724800","keepAlive":75,"maxWorkerConnections":16384,"proxyConnectTimeout":5,"proxyReadTimeout":60,"proxyRealIpCidr":"0.0.0.0/0","proxySendTimeout":60,"retryNonIdempotent":false,"serverNameHashBucketSize":256,"serverNameHashMaxSize":512,"skipAccessLogUrls":[],"sslBufferSize":"4k","sslCiphers":"ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA","sslProtocols":"TLSv1 TLSv1.1 TLSv1.2","sslRedirect":true,"sslSessionCache":true,"sslSessionCacheSize":"10m","sslSessionTickets":true,"sslSessionTimeout":"10m","useGzip":true,"useHttp2":true,"vtsStatusZoneSize":"10m","whitelistSourceRange":[],"workerProcesses":"1"},"customErrors":false,"defResolver":"25.0.0.10","servers":[{"Name":"_","Locations":[{"Path":"/","IsDefBackend":true,"Upstream":{"Name":"upstream-default-backend","Backends":[{"Address":"25.1.36.2","Port":"8080","MaxFails":0,"FailTimeout":0},{"Address":"25.1.39.2","Port":"8080","MaxFails":0,"FailTimeout":0},{"Address":"25.1.66.2","Port":"8080","MaxFails":0,"FailTimeout":0}],"Secure":false},"Auth":{"Type":"","Realm":"","File":"","Secured":false},"RateLimit":{"Connections":{"Name":"","Limit":0,"Burst":0,"SharedSize":0},"RPS":{"Name":"","Limit":0,"Burst":0,"SharedSize":0}},"Redirect":{"Target":"","AddBaseURL":false,"SSLRedirect":false},"SecureUpstream":false,"Whitelist":{"CIDR":null}}],"SSL":false,"SSLCertificate":"","SSLCertificateKey":"","SSLPemChecksum":""}],"sslDHParam":"","tcpUpstreams":[],"udpUpstreams":[],"upstreams":[{"Name":"upstream-default-backend","Backends":[{"Address":"25.1.36.2","Port":"8080","MaxFails":0,"FailTimeout":0},{"Address":"25.1.39.2","Port":"8080","MaxFails":0,"FailTimeout":0},{"Address":"25.1.66.2","Port":"8080","MaxFails":0,"FailTimeout":0}],"Secure":false}]}
E0728 18:22:05.127121       1 runtime.go:58] Recovered from panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/ingress/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:52
/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/ingress/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:40
/usr/lib/google-golang/src/runtime/asm_amd64.s:479
/usr/lib/google-golang/src/runtime/panic.go:458
/usr/lib/google-golang/src/text/template/exec.go:140
/usr/lib/google-golang/src/runtime/asm_amd64.s:479
/usr/lib/google-golang/src/runtime/panic.go:458
/usr/lib/google-golang/src/runtime/panic.go:62
/usr/lib/google-golang/src/runtime/sigpanic_unix.go:24
/usr/lib/google-golang/src/text/template/exec.go:186
/usr/lib/google-golang/src/text/template/exec.go:175
/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/ingress/controllers/nginx/nginx/template.go:83
/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/ingress/controllers/nginx/nginx/command.go:65
/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/ingress/controllers/nginx/controller.go:461
/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/ingress/controllers/nginx/controller.go:150
/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/ingress/controllers/nginx/utils.go:90
/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/ingress/controllers/nginx/utils.go:64
/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/ingress/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:86
/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/ingress/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:87
/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/ingress/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:49
/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/ingress/controllers/nginx/utils.go:64
/usr/lib/google-golang/src/runtime/asm_amd64.s:2086
```

Thoughts?

UPDATE: this is clearly a problem with my template (which I'm injecting via volume mounted configmap) trying to figure out if it's the template itself (probable).

Confirmed this was a problem in my template,  a nicer error message might be helpful here.

### PR DESCRIPTION
**Pull request by aledbf**
fixes #1448

### CODE REVIEW

File: ingress/controllers/nginx/nginx/main.go [hunk 1]
```diff
@@ -67,7 +67,9 @@ func NewManager(kubeClient *client.Client) *Manager {
 
 	ngx.sslDHParam = ngx.SearchDHParamFile(config.SSLDirectory)
 
-	ngx.loadTemplate()
+	if err := ngx.loadTemplate(); err != nil {
+		glog.Fatalf("invalid NGINX template: %v", err)
```
Comment (bprashanth) [inline ingress/controllers/nginx/nginx/main.go]: do you really want to fatal when a load fails? isn't this different from what nginx usually does? meanign if you have a working config and you overwrite it with some invalid config, nginx will keep working with the old config right?

Comment (bprashanth) [inline ingress/controllers/nginx/nginx/main.go]: I'm specifically asking about what we should do if someone modifies the template to have a syntax error. I think the answer is we should do whatever nginx would do if someone modified the nginx.conf to have a syntax error.

Comment (aledbf) [inline ingress/controllers/nginx/nginx/main.go]: > do you really want to fatal when a load fails? 

Only the first time is loaded (in case someone uses a custom template)

>  I think the answer is we should do whatever nginx would do if someone modified the nginx.conf to have a syntax error.

If the template cannot be loaded the pod will fail the health checks (crashloop) and the log doesn't help (check the output of 1448).

Comment (bprashanth) [inline ingress/controllers/nginx/nginx/main.go]: so we don't watch the custom template? failing on first failure to load is fine, I'm more concerned with what happens if i:
1. kubectl exec and overwrite template
2. endpoints change

do we crashloop, or keep using the old template (sounds like we keep using the old template, meaning we ignore updates to the config map. that's fine as long as it's clear in the doc)?

Comment (aledbf) [inline ingress/controllers/nginx/nginx/main.go]: > so we don't watch the custom template?

nop, we keep using the old template. 

I'll add a watch to the template file to cover:
1. kubectl exec and overwrite template
2. update in the config map (mounted template)

if there's an error log the error and keep using the working version of the template

**Comment by bprashanth** [comment]
LGTM assume you're going to make proposed changes in a follow up pr
