### PR TITLE
Possibly fix JSON complaining about channels?

### LINKED ISSUE #78: Submit queue ui is borken
/api says
```
json: unsupported type: <-chan struct {}
```
@lavalamp

### PR DESCRIPTION
**Pull request by lavalamp**
Maybe fix #78?

### CODE REVIEW

**Comment by lavalamp** [comment]
@brendandburns

**Comment by brendandburns** [comment]
LGTM, I don't understand where that channel is coming from, that object is serialized to JSON by go-github afaik...

**Comment by brendandburns** [comment]
Also, see #99

File: submit-queue/e2e.go [hunk 1]
```diff
@@ -30,9 +30,24 @@ import (
 	github_api "github.com/google/go-github/github"
 )
 
+// PRInfo explicitly collects the fields we wish to encode via JSON.
+type PRInfo struct {
+	Number *int    `json:"number"`
+	URL    *string `json:"html_url"`
```
Comment (eparis) [inline submit-queue/e2e.go]: I don't even know what the problems are here, but why not make this an `int` and `string` instead of `*int` and `*string` so you know the PRInfo can't mutate after it's created?

Comment (lavalamp) [inline submit-queue/e2e.go]: I can change it if you feel strongly, but I'm pretty sure everyone treats those as read-only; they're pointers only because they are optional.

Comment (eparis) [inline submit-queue/e2e.go]: I don't feel strongly at all.
